

experim_name: 'default'
################################################################################
# training parameters
################################################################################
pretrained_root: 'checkpoints'
n_gpu: 1
root: '/home/tiago/Dropbox/research-projects/orchards-uk/dataset'
root_ws: "C:\\Users\\Tiago\\TB\\datasets"

retrieval:
  top_cand: [1,5,25]
  range_thres: 6

train_loader:
  data:
    dataset: ''
    sequence: 'autumn'
    aug: False
    modality: 'range'
    max_points: 10000
  
  ground_truth: 
    pos_range: 2 # Loop Threshold [m]
    neg_range: 10
    num_neg: 20
    num_pos: 1
    warmupitrs: 600 # Number of frames to ignore at the beguinning
    roi: 500 
    #pos_range: 5
    #neg_range: 20
  fraction: 0.3 
  batch_size: 1       # batch size
  shuffle: True
  #rotation: [180,-45,-45]
  
val_loader:
  data:
    dataset: ''
    sequence: 'summer'
    modality: 'range' # ['range',projection,bev]'intensity','density','height','bev']
    max_points: 10000

  ground_truth: 
    pos_range: 2 # Loop Threshold [m]
    neg_range: 10
    num_neg: 0
    num_pos: 50
    warmupitrs: 600 # Number of frames to ignore at the beguinning
    roi: 500 

  batch_size: 1 #50         # batch size
  workers:  0            # number of threads to get data
  shuffle: False
  #rotation: [180,-45,-45]

model:
  type: 'AttVLAD_resnet50'
  minibatch_size: 10
  pretrained_backbone: True
  output_dim: 256
  use_tnet: False
  #in_channels: 1

bev_param:
  in_channels: 3
  max_samples: 256
  cluster_size: 64

height_param:
  in_channels: 1
  max_samples: 128
  cluster_size: 64

rp_param:
  in_channels: 5
  max_samples: 64
  cluster_size: 64

range_param:
  in_channels: 1
  max_samples: 64
  cluster_size: 20

pcl_param:
  in_channels: 1
  max_samples: 128
  cluster_size: 64

loss:
  type: 'TripletLoss'
  args:
    margin: 0.5
    metric: 'L2' # [L2,Hinge,cosine,kl_divergence]
    reduction: 'mean'


trainer:
  iter_per_epoch: 1
  epochs: 1000
  report_val: 1        # every x epochs, report validation set
  save_period: 1
  log_dir: "saved/"
  save_dir: "checkpoints/"
  monitor: "max recall" # [off, max mIoU]
  val_per_epochs: 1
  eval_metric: 'L2'
  results_dir: "/media/tiago/BIG/Orchards/temp/"


optimizer:
  type: "AdamW" #[RMSprop,Adam,SGD]
  args:
    lr: 0.01
    weight_decay: 0.0005
  lr_scheduler: "ReduceLROnPlateau"

StepLR:
  step_size: 20 
  gamma: 0.1

CosineAnnealingWarmRestarts:
  T_0: 5
  T_mult: 2
  eta_min: 0.00001 # Min learning rate


ReduceLROnPlateau:
  mode: 'min' #['min','max'] (str)
  factor: 0.01
  patience: 5 # Number of epochs with no improvement after which learning rate will be reduced. 
  min_lr: 0.000001

